spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_paroquia
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

api.v1.mercadopago-accesstoken=APP_USR-3853433899421639-052010-afcbbc0460efdfaa889db6d1fedcf441-3415653122
api.v1.mercadopago-notification-url=